### ISSUE TITLE
Friend Req, Invite が表示されない

### ISSUE THREAD

**Issue by kobi32768** [nukora/VRChatActivityTools#13]
IK-Beta にて

* Friend Request (Receive)
* Invite (Send)

~~の情報が取得できていなかった~~
の情報が表示されていなかった

~~ログファイルと `VRChatActivityLogger/VRChatActivityLogger/RegexPatterns.cs` の `RegexPatterns()` を参照した限りログのフォーマットがどこかのバージョンで変わっている可能性がある~~
~~他の動作についても確認していないが変更が加えられている可能性は十分にあると思われる~~

~~Friend Request のログと思われるものを載せておきます~~
```
2022.02.27 18:05:48 Log        -  AcceptNotification for notification:<Notification from username:XXXXXX, sender user id:usr_XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX to usr_XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX of type: friendRequest, id: frq_XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX, created at: 02/27/2022 09:05:44 UTC, details: {{}}, type:friendRequest, m seen:True, message: "">
```

コードに関しては確認不足でした
しかし表示はされていないようです

Beta での報告で申し訳ないです

**Comment by nukora** [comment]
Issueありがとうございます！

去年の4月あたりからVRChatクライアントが以下のログを出力しなくなってしまった為、
過去データは参照できるが新規にデータを取得できないという状況になっているはずです。
- Invite (Send)
- Request Invite (Send)
- Friend Request (Send)
- Invite (Receive)
- Request Invite (Receive)
- Friend Request (Receive)
- Invite Response (Receive)
- Request Invite Response (Receive)

貼って頂いたログは「フレンドリクエストを許可した」というログで、Friend Request (Accept)として記録されているはずですが、もしそちらも記録されていなければ調査します。

**Comment by kobi32768** [comment]
Join と Meet しか記録されてませんでした
あまりそれ以外の動作をしていないというのもありますが
Friend Request の Send, Receice, Accept と、これらのすべての動作はしたはずなのですが記録されてませんでした

**Comment by nukora** [comment]
改めてログを調査したところ、いつからかFriend Request (Accept)のフォーマットが変わってしまっているようでした。
こちら修正したいと思います。

また、新規にInvite (Accept)とRequest Invite (Accept)のログが取得できそうなので、こちらの機能追加も行います。

それ以外のログについては現在では取得できないのですが、旧機能として残しておくつもりです。

**Comment by nukora** [comment]
実装しました。
